version: '2'
services:
        mongo:
                image: mongo:4
                ports:
                        - 27017:27017
        redis:
                image: redis:5
                ports:
                        - 6379:6379

