version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npx @karimsa/mono
      - run:
          name: Run tests
          command: npx @karimsa/mono test
